### ISSUE TITLE
how to make ch/raw/ph files?

### ISSUE THREAD

**Issue by JobsSteve** [Nirklav/Tanks#6]

**Comment by Nirklav** [comment]
**.ch** - it's file which contains one serialized object (ObjectOutputStream). It can be ArrayList<String> (in folder Content) or class which is inherit from Description class (Descriptions folder).

**.raw** - it's files form Blender. [Format description of .raw file in comment](https://github.com/Nirklav/Tanks/blob/master/app/src/main/java/com/ThirtyNineEighty/Base/Resources/Sources/FileGeometrySource.java). 

**.ph** file format same as .raw but one polygon consists from four packs instead of three in .raw. And pack not contain normal and texture coord.

You can visit [source](https://github.com/Nirklav/Tanks/tree/master/app/src/main/java/com/ThirtyNineEighty/Base/Resources/Sources)/[source ](https://github.com/Nirklav/Tanks/tree/master/app/src/main/java/com/ThirtyNineEighty/Game/Resources/Sources) folder in project and view all sources of classes which do load of resource.

**Comment by JobsSteve** [comment]
thanks and I will check the related source. Sorry for my late reply.
